-- Таблица пользователей
CREATE TABLE users (
    id SERIAL PRIMARY KEY, 
    user_name VARCHAR(255) NOT NULL, 
    user_surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE, 
    password VARCHAR(255) NOT NULL, 
    roles VARCHAR(255) NOT NULL, 
    name_company VARCHAR(255) UNIQUE,
    address_company VARCHAR(255) UNIQUE, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

-- Таблица постов
CREATE TABLE posts (
    id SERIAL PRIMARY KEY, 
    title VARCHAR(255) NOT NULL, 
    description TEXT NOT NULL, 
    tags VARCHAR(255), 
    recruiter_id INT REFERENCES users(id) ON DELETE CASCADE, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);
